### PR TITLE
Change cypher to match description

### PR DESCRIPTION
**Pull request by jamthief**
A couple of proposed minor edits.

### CODE REVIEW

**Comment by martinohanlon** [comment]
re `MATCH (p:Person {name: 'Michael Caine'})`

The cypher used in the "Read" version of the lesson uses the same cypher as in the video. I think there is benefit to leaving it the same. The Cypher achieves the same and it demonstrates that MERGE can be used in place of MATCH to update / retrieve. 

re `SET r.roles = ['Alfred Penny'], m.released = 2008`

I can see what the original author was trying to do, adding 2 properties to the same entity simplifies it. Interestingly the video doesnt cover this. I can see the benefit of doing this though.

**Comment by jamthief** [comment]
> `MATCH (p:Person {name: 'Michael Caine'})`
> The Cypher achieves the same and it demonstrates that MERGE can be used in place of MATCH to update / retrieve.

That's true! Perhaps we could call it out here, then? The text reads

> We *find* the Person node and we *create* the Movie node.  _(emphasis mine)_

but maybe we could add modify this section to emphasise the point about MERGE being able to do both.

> SET r.roles = ['Alfred Penny'], m.released = 2008

My proposal here is merely to change the SET statement away from using `r.year` here, which doesn't fit the inferred schema of the movies DB (did it change maybe?). `m.released` is consistent with said schema.

**Comment by jamthief** [comment]
re `SET r.roles = ['Alfred Penny'], m.released = 2008`

My proposal here is merely to change the SET statement away from using `r.year` here, which doesn't fit the inferred schema of the movies DB (did it change maybe?). `m.released` is consistent with said schema.

**Comment by martinohanlon** [comment]
> That's true! Perhaps we could call it out here. Maybe this?

```
In this code, the actor, _Michael Caine_ exists but the movie, _Batman Begins_ does not. MERGE is used to find and update the _Person_ node and create the _Movie_ node.
```

> re SET r.roles = ['Alfred Penny'], m.released = 2008

Yep, happy with that.

**Review by martinohanlon — APPROVED** [review]

**Comment by martinohanlon** [comment]
I'll merge when we next do a release.

**Pull request merged**
